
server:
  port: 8080
#  servlet:
#    context-path: /${spring.application.name}
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace:
        file-extension: yaml # 配置文件格式
      discovery:
        server-addr: 127.0.0.1:8848
#        register-enabled: true
#        enabled: true

#    gateway:
      # 自动路由
#      discovery:
#        locator:
#          # enabled：默认为false，设置为true表明spring cloud gateway开启服务发现和路由的功能，网关自动根据注册中心的服务名为每个服务创建一个router，将以服务名开头的请求路径转发到对应的服务
#          enabled: true
#          # lowerCaseServiceId：启动 locator.enabled=true 自动路由时，路由的路径默认会使用大写ID，若想要使用小写ID，可将lowerCaseServiceId设置为true
#          lower-case-service-id: true
      # 路由数组：指当请求满足什么样的断言时，转发到哪个服务上
#      routes:
#        # 路由标识，要求唯一，名称任意
#        - id: consumer
#          # 请求最终被转发到的目标地址
##          uri: http://localhost:8763  # consumer服务
#          uri: lb://consumer // 负载均衡需要添加spring-cloud-loadbalancer依赖
#          # 设置断言
#          predicates:
#            # Path Route Predicate Factory 断言，满足 /gateway/provider/** 路径的请求都会被路由到 http://localhost:9024 这个uri中
##            - Path=/consumer/hello/**
#            - Path=/consumer/**
#            # Weight Route Predicate Factory 断言，同一分组按照权重进行分配流量，这里分配了80%
#            # 第一个group1是分组名，第二个参数是权重
##            - Weight=group1, 8
#          # 配置过滤器（局部）
#          filters:
#            # StripPrefix：去除原始请求路径中的前1级路径，即/gateway
#            - StripPrefix=1
##
#        - id: provider
##          uri: http://localhost:8762
#          uri: lb://provider
#          # 设置断言
#          predicates:
##            - Path=/provider/hello/**
#            - Path=/provider/**
#            # Weight Route Predicate Factory，同一分组按照权重进行分配流量，这里分配了20%
##            - Weight=group1, 2
#          # 配置过滤器（局部）
#          filters:
#            # StripPrefix：去除原始请求路径中的前1级路径，即/gateway
#            - StripPrefix=1
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 动态路由配置
route:
  dynamic:
    enabled: true
    # 注意如果不写就是默认的，填其他命名空间的话需要填写Id而不是名称
    namespace:
    dataId: gateway_route
    group: DEFAULT_GROUP