server:
  port: 8762
#  servlet:
#    context-path: /${spring.application.name}

spring:
  application:
    name: provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
